version: '3'
services:

  proxy:
    build:
      context: ./envoy
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  server:
    build:
      context: ./audioNode
      dockerfile: Dockerfile
    volumes:
      - audio:/audioNode/audio
    ports:
      - "8080:8080"
    depends_on:
      - proxy
  docker-manager:
    build:
        context: ./dockerManager
        dockerfile: Dockerfile
    ports:
      - "8180:8180"
    depends_on:
      - proxy
volumes:
  audio:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/Desktop/Techno

# web-client:
  #build:
  #  context: ./
  #  dockerfile: Dockerfile
  # ports:
  #  - "4000:4000"
  # depends_on:
  #  - server
  #  - proxy
