version: '3'
services:

  proxy:
    build:
      context: ./envoy
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  server:
    build:
      context: ./analyzer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - proxy

  web-client:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - server
      - proxy
    tty: true
